name: Check Agda Files

on:
  schedule:
    # Runs twice a day at 08:00 and 18:00 BRT
    - cron: '0 11,21 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  check-all-agda: 
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "PATH=$PATH:/usr/local/bin:/home/runner/.local/bin" >> $GITHUB_ENV

      - name: Verify Agda and agda-cli installations
        run: |
          agda --version
          which agda-cli

      - name: Run Agda checks
        id: check_agda
        run: | 
          OK_OUTPUT=$'Checked.\nNo output'

          check_file() {
            file="$1"	
            output=$(agda-cli check "$file" 2>&1)
            if [ "$output" = "$OK_OUTPUT" ]; then
              echo "Checked $file: OK"
            else
              echo -e "\033[31mChecking: $file ERR\033[0m"
              echo "$output"
              {
                echo "Checking: $file ERR"
                echo "$output"
                echo ""
              } >> error_output.log
              echo "errors_found=true" >> $GITHUB_ENV
            fi 
          }
          export -f check_file
          export OK_OUTPUT

          > error_output.log

          find "./Base" -name "*.agda" -not -path "*.tmp*" -not -path "*/Test/*" -print0 | \
            parallel -0 -j 96 check_file

          if [ -s error_output.log ]; then
            echo "error_output<<EOF" >> $GITHUB_OUTPUT
            cat error_output.log >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        timeout-minutes: 10


      - name: Find existing issue
        id: find_existing_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              });
            const existingIssue = issues.find(issue => 
              issue.title === "Agda Check Errors (Auto-generated)" && issue.user.login === 'github-actions[bot]' && issue.labels.some(label => label.name === 'errors')
            );
            return existingIssue ? existingIssue.number : null;
          result-encoding: string
            
      - name: Create or update issue
        if: env.errors_found == 'true'
        uses: peter-evans/create-issue-from-file@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Agda Check Errors (Auto-generated)"
          content-filepath: ./error_output.log
          labels: |
            errors
            automated
          issue-number: ${{ steps.find_existing_issue.outputs.result }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Issue Number
        if: ${{ steps.find_existing_issue.outputs.result == '' && env.errors_found == 'true' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = {{ steps.create_or_update_comment.outputs.issue_number }};
            fs.writeFileSync('.issue_number', issue_number);

      - name: Upload output as an artifact
        if: env.errors_found == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: agda-check-output
          path: error_output.log

      - name: Clean up
        run: rm -f error_output.log

